name: Clone Other Repo
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Clone Ops Repo and Update the repo
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://github.com/akashbhardwaj23/ops.git
          cd ops
          sed -i 's|image: akashbhardwaj24/chainexplorer:.*|image: akashbhardwaj24/chainexplorer:${{ github.sha }}|' staging/chainexplorer/deployment.yml
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add staging/chainexplorer/deployment.yml
          git commit -m "Update chainexplorer image to ${{ github.sha }}"
          git push https://${PAT}@github.com/akashbhardwaj23/ops.git main
