name: Continous Deployment
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker Login
        uses : docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set Up Docker build
        uses: docker/setup-buildx-action@v2

      - name: Build Docker File
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: akashbhardwaj24/chainexplorer:${{ github.sha }}

      - name: Clone Ops Repo and Update the repo
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://github.com/akashbhardwaj23/ops.git
          cd ops
          sed -i 's|image: akashbhardwaj24/chainexplorer:.*|image: akashbhardwaj24/chainexplorer:${{ github.sha }}|' staging/chainexplorer/deployment.yml
          git config user.name "Github Action Bot"
          git config user.email "github@actionbot.com"
          git add staging/chainexplorer/deployment.yml
          git commit -m "Updated Image chainexplorer to ${{ github.sha }}"
          git push https://${PAT}@github.com/akashbhardwaj23/ops.git main
